//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechFixWeb.SupplierServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SupplierServiceReference.SupplierWebServiceSoap")]
    public interface SupplierWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewItems", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ViewItems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewItems", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ViewItemsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertProduct", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertProduct(string productName, string supplierName, string description, decimal price, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<string> InsertProductAsync(string productName, string supplierName, string description, decimal price, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteProduct", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DeleteProduct(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<string> DeleteProductAsync(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProduct", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateProduct(int productId, string productName, string SupplierName, string description, decimal price, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<string> UpdateProductAsync(int productId, string productName, string SupplierName, string description, decimal price, int quantity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SupplierWebServiceSoapChannel : TechFixWeb.SupplierServiceReference.SupplierWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SupplierWebServiceSoapClient : System.ServiceModel.ClientBase<TechFixWeb.SupplierServiceReference.SupplierWebServiceSoap>, TechFixWeb.SupplierServiceReference.SupplierWebServiceSoap {
        
        public SupplierWebServiceSoapClient() {
        }
        
        public SupplierWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SupplierWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SupplierWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SupplierWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable ViewItems() {
            return base.Channel.ViewItems();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ViewItemsAsync() {
            return base.Channel.ViewItemsAsync();
        }
        
        public string InsertProduct(string productName, string supplierName, string description, decimal price, int quantity) {
            return base.Channel.InsertProduct(productName, supplierName, description, price, quantity);
        }
        
        public System.Threading.Tasks.Task<string> InsertProductAsync(string productName, string supplierName, string description, decimal price, int quantity) {
            return base.Channel.InsertProductAsync(productName, supplierName, description, price, quantity);
        }
        
        public string DeleteProduct(int productId) {
            return base.Channel.DeleteProduct(productId);
        }
        
        public System.Threading.Tasks.Task<string> DeleteProductAsync(int productId) {
            return base.Channel.DeleteProductAsync(productId);
        }
        
        public string UpdateProduct(int productId, string productName, string SupplierName, string description, decimal price, int quantity) {
            return base.Channel.UpdateProduct(productId, productName, SupplierName, description, price, quantity);
        }
        
        public System.Threading.Tasks.Task<string> UpdateProductAsync(int productId, string productName, string SupplierName, string description, decimal price, int quantity) {
            return base.Channel.UpdateProductAsync(productId, productName, SupplierName, description, price, quantity);
        }
    }
}
